# Generated by Django 5.0.7 on 2024-07-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
