# Generated by Django 5.0.7 on 2024-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_rental_user_name_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(default='unknown', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
